### ISSUE TITLE
Who shot the Moon?

### ISSUE THREAD

**Issue by amorriscode** [hyshka/moonshot#4]
Murder mystery. Someone has murdered the Moon! You're the best Intergalactic Space Detective and you're hired to solve the crime.

**Comment by amorriscode** [comment]
Could be a point & click/choose your own adventure with little mini games baked in.

**Comment by hyshka** [comment]
With a point and click, maybe be able to have more time for cool visualizations and create more ambience

**Comment by amorriscode** [comment]
@hyshka definitely could focus on our storytelling skills for sure.
