### ISSUE TITLE
Lunar Safari

### ISSUE THREAD

**Issue by amorriscode** [hyshka/moonshot#5]
Puzzle game where you have to go take photographs on the newly settled Moon. Like Pokémon Snap but on the Moon or in space.

**Comment by hyshka** [comment]
You could get points for capturing certain craters or stars.

Also could do a review system where other players rate your snaps.

Would also be good to focus on the visuals for this one.

**Comment by amorriscode** [comment]
This is my least favourite idea so far. :)

**Comment by hyshka** [comment]
lol I like this one. In my mind, it'd be cool because you'd just get to look at awesome space visuals. That said, you would have to nail the visuals to make it feel like you're in Interstellar or something.

Would definitely need a good soundtrack as well.
